//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nasa.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar registro..
        /// </summary>
        public static string ERR_FalhaAtualizarRegistro {
            get {
                return ResourceManager.GetString("ERR_FalhaAtualizarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na autenticação..
        /// </summary>
        public static string ERR_FalhaAutenticacao {
            get {
                return ResourceManager.GetString("ERR_FalhaAutenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao inserir registro..
        /// </summary>
        public static string ERR_FalhaInserirRegistro {
            get {
                return ResourceManager.GetString("ERR_FalhaInserirRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha interna..
        /// </summary>
        public static string ERR_FalhaInterna {
            get {
                return ResourceManager.GetString("ERR_FalhaInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao recuperar registro..
        /// </summary>
        public static string ERR_FalhaRecuperarRegistro {
            get {
                return ResourceManager.GetString("ERR_FalhaRecuperarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao recuperar registros..
        /// </summary>
        public static string ERR_FalhaRecuperarRegistros {
            get {
                return ResourceManager.GetString("ERR_FalhaRecuperarRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao remover registro..
        /// </summary>
        public static string ERR_FalhaRemoverRegistro {
            get {
                return ResourceManager.GetString("ERR_FalhaRemoverRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Data não reconhecido..
        /// </summary>
        public static string ERR_FormatoDataNaoReconhecido {
            get {
                return ResourceManager.GetString("ERR_FormatoDataNaoReconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido ou expirado..
        /// </summary>
        public static string ERR_NaoAutorizadoTokenInvalidoExpirado {
            get {
                return ResourceManager.GetString("ERR_NaoAutorizadoTokenInvalidoExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível processar solicitação.
        /// </summary>
        public static string ERR_NaoFoiPossivelProcessarSolicitacao {
            get {
                return ResourceManager.GetString("ERR_NaoFoiPossivelProcessarSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Primária já existente..
        /// </summary>
        public static string ERR_PkExiste {
            get {
                return ResourceManager.GetString("ERR_PkExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Primária não informada..
        /// </summary>
        public static string ERR_PkNaoInformada {
            get {
                return ResourceManager.GetString("ERR_PkNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado..
        /// </summary>
        public static string ERR_RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("ERR_RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro referenciado {0}.
        /// </summary>
        public static string ERR_RegistroReferenciado {
            get {
                return ResourceManager.GetString("ERR_RegistroReferenciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação Negada..
        /// </summary>
        public static string ERR_SolicitacaoNegada {
            get {
                return ResourceManager.GetString("ERR_SolicitacaoNegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token não reconhecido..
        /// </summary>
        public static string ERR_TokenNaoReconhecido {
            get {
                return ResourceManager.GetString("ERR_TokenNaoReconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username já registrado..
        /// </summary>
        public static string ERR_UsernameRegistrado {
            get {
                return ResourceManager.GetString("ERR_UsernameRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação encerrada com sucesso.
        /// </summary>
        public static string INF_OperacaoEncerradaComSucesso {
            get {
                return ResourceManager.GetString("INF_OperacaoEncerradaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso..
        /// </summary>
        public static string INF_RegistroAtualizadoSucesso {
            get {
                return ResourceManager.GetString("INF_RegistroAtualizadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro criado com sucesso..
        /// </summary>
        public static string INF_RegistroCriadoSucesso {
            get {
                return ResourceManager.GetString("INF_RegistroCriadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro removido com sucesso..
        /// </summary>
        public static string INF_RegistroRemovidoSucesso {
            get {
                return ResourceManager.GetString("INF_RegistroRemovidoSucesso", resourceCulture);
            }
        }
    }
}
